@startuml

' Modelo de domínio combinado (classes de análise - atributos e associações)

abstract class Usuario {
    id: Integer
    nome: String
    email: String
    senha: String
    telefone: String
    perfil: String
    cpf: String
    dataNascimento: Date 
}

class Medico {
    crm: String
    especialidade: String 
}

class Paciente { 
    ' Herda atributos de Usuario
}

class Consulta {
    id: Integer
    dataHora: DateTime
    status: String 
}

class DocumentoMedico {
    idDocumento: Integer
    nomeArquivo: String
    tipoArquivo: String
    dataUpload: Date 
}

class Ambiente3D {
    id: Integer
    descricao: String 
}

class AnotacaoMedica {
    id: Integer
    texto: String
    dataHoraCriacao: LocalDateTime
    dataHoraUltimaEdicao: LocalDateTime
    medico: Medico
    paciente: Paciente
}

class Mensagem {
    id: Integer
    texto: String
    dataHoraEnvio: LocalDateTime
    remetente: Usuario
    destinatario: Usuario
}

' Herança Usuario <|-- Medico Usuario <|-- Paciente

' Associações Medico "1" -- "0.." Consulta : realiza Paciente "1" -- "0.." Consulta : participa Consulta "1" -- "1" Ambiente3D : possui Paciente "1" -- "0.." DocumentoMedico : envia Consulta "1" -- "0.." AnotacaoMedica : possui Consulta "1" -- "0..*" Mensagem : possui

@enduml